# Generated by Django 4.2.4 on 2023-12-15 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_alter_blocked_blocked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
