# Generated by Django 4.2.4 on 2023-12-15 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_alter_blocked_blocked_user_alter_blocked_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blockeds_blocked_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blockeds_to_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contacts_to_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contacts_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
