# Generated by Django 4.2.4 on 2023-12-04 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(db_column='from_id', on_delete=django.db.models.deletion.CASCADE, related_name='Chats_from_id', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.CASCADE, related_name='Chats_to_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('hidden_for_from_id', models.BooleanField(default=False)),
                ('hidden_for_to_id', models.BooleanField(default=False)),
                ('attachment_code', models.CharField(max_length=45, null=True)),
                ('attachment_id', models.IntegerField(null=True)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatMessages_chat_id', to='chats.chats')),
                ('from_user', models.ForeignKey(db_column='from_id', on_delete=django.db.models.deletion.CASCADE, related_name='ChatMessages_from_id', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.CASCADE, related_name='ChatMessages_to_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
