# Generated by Django 4.2.4 on 2023-12-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_alter_chat_from_user_alter_chat_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatMessages_from_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatMessages_to_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
